[package]
name = "rsf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "clientbt"
path = "src/clientbt.rs"

[[bin]]
name = "serverbt"
path = "src/serverbt.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
